### ISSUE TITLE
`doctr_det_predictor` failed installation without conda

### ISSUE THREAD

**Issue by shingjan** [pytorch/benchmark#1512]
with #1496, now torchbenchmark will fail the installation of `doctr_det_predictor` if `conda` is not installed. This looks like a breaking change as `conda` is explicitly mentioned as a optional, instead of required, dependency of `torchbench`.

cc: @xuzhao9

**Comment by xuzhao9** [comment]
Thanks for the feedback. I am leaning to change `conda` to a hard requirement because `doctr_det_predictor` requires the `libglib` version provided in the `conda-forge` repo. Although users can install `libglib` provided by their OS, the version might not be compatible to the version accepted by `doctr_det_predictor` and will complicate the user's installation process. What do you think? 

Also cc the PR author @janeyx99

**Comment by shingjan** [comment]
I feel like making `conda` a hard requirement just for one model is likely an overkill if there could be a workaround. If not then probably `conda` is the only way to go. `conda` also ships with some outdated runtimes so I will recommend to steer away from `conda` if possible.

BTW what about not failing the whole `python install.py` if some requirements of a model is not met? Like a graceful exit and warning about a specific model not available due to unmet dependencies.

**Comment by janeyx99** [comment]
I think adding a warning here will be sufficient, as I understand that others like @shingjan may want to avoid conda for the reasons mentioned.
