### ISSUE TITLE
[Question] What benchmarks does pytorch use to test a release?

### ISSUE THREAD

**Issue by sallyseok** [pytorch/benchmark#1965]
Hi, I am running benchmarks for pytorch 2.1.0 on AWS hardware and I want to confirm which benchmarks/models were used by upstream pytorch for the release.
Do you use [userbenchmark/torch-nightly](https://github.com/pytorch/benchmark/tree/v3.0/userbenchmark/torch-nightly) to test the nightlies, then [userbenchmark/release-test/run_release_test.sh](https://github.com/pytorch/benchmark/blob/main/userbenchmark/release-test/run_release_test.sh) before the official release? I see that `torch-nightly` has much more models than `run_release_test.sh` does; are the models in `run_release_test.sh` sufficient for a release?

**Comment by xuzhao9** [comment]
For the release we only use the `release-test` userbenchmark, because it tests end-to-end models which involves multiple batches, data loading, etc.

At the same time, we use `torch-nightly` to run more models on nightly release to prevent regressions, but `torch-nightly` only runs single-batch, module-level tests, the data is prefetched to the device so the dataloading is not involved.

cc @atalman is there any plan to build broader release test?

**Comment by atalman** [comment]
@xuzhao9 , @sallyseok . The torch-nightly tests detect nightly regressions and run on nightly basis. For release-test we run them few times before the release and compare basic performance regression between the releases. I agree we should also probably include torch-nightly tests within release testing. We do have plan on improving release perf testing for H1 2024.
