### ISSUE TITLE
`DALLE2_pytorch` moved to `canary_models` due to NumPy 2.0 upgrade.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/benchmark#2339]
In #2311, `DALLE2_pytorch` benchmark was moved into `canary_models` due to the NumPy 2.0 upgrade. I'm opening this issue for tracking the progress towards moving it back to the `models` folder.

**Comment by xuzhao9** [comment]
We remove `DALLE2_pytorch` because the upstream model depends on `embedding-reader`, which further depends on numpy<2: https://github.com/rom1504/embedding-reader/blob/a4fd55830a502685600ed8ef07947cd1cb92b083/requirements.txt#L3

Unless this is fixed by upstream repos, we can't really add back this model.
